name: home_cache
description: "Home Cache"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  image_picker: ^1.1.2
  table_calendar: ^3.2.0
  #  speech_to_text: ^7.2.0
  wechat_assets_picker: ^9.4.2
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.5
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.2
  pie_chart: ^5.4.0
  flutter_credit_card: ^4.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LeagueSpartan-Black.ttf
          weight: 900
